---
platform: linux

inputs:
- name: git-pipeline
- name: git-user
  optional: true
- name: git-orders
  optional: true
- name: current-app-info

run:
  path: ./git-pipeline/deploy/cloud-foundry/ci/tasks/load-tests
