---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/dynatrace-cli
    tag: "latest"

inputs:
- name: git-pipeline
- name: current-app-info
- name: git-user
  optional: true
- name: git-orders
  optional: true

run:
  path: ../git-pipeline/deploy/cloud-foundry/ci/tasks/push-dynatrace-monspec-data