---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: git-pipeline
- name: git-user
  optional: true
- name: git-orders
  optional: true
- name: current-app-info

run:
  path: ./PivotalDevOpsTutorial/ci/tasks/update-routes
